export const categories = [
  {
    name: 'Pizza',
    slug: 'pizza',
    description: 'Delicious pizzas with various toppings',
    isActive: true,
    sortOrder: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo',
    slug: 'combo',
    description: 'Value meal combos',
    isActive: true,
    sortOrder: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Khai vị',
    slug: 'khai-vi',
    description: 'Appetizers and starters',
    isActive: true,
    sortOrder: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Đồ uống',
    slug: 'do-uong',
    description: 'Refreshing beverages',
    isActive: true,
    sortOrder: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cà phê',
    slug: 'ca-phe',
    description: 'Coffee drinks',
    isActive: true,
    sortOrder: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mỳ Ý',
    slug: 'my-y',
    description: 'Italian pasta dishes',
    isActive: true,
    sortOrder: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const ingredients = [
  {
    name: 'Viền phô mai',
    description: 'Cheese-stuffed crust',
    price: 179000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/99f5cb91225b4875bd06a26d2e842106.png',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mozzarella kem',
    description: 'Creamy mozzarella cheese',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/cdea869ef287426386ed634e6099a5ba.png',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Phô mai Cheddar',
    description: 'Sharp cheddar cheese',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA69C1FE796',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ớt Jalapeno cay',
    description: 'Spicy jalapeno peppers',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/11ee95b6bfdf98fb88a113db92d7b3df.png',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Gà mềm',
    description: 'Tender chicken',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA5B328D35A',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Nấm mỡ',
    description: 'Fresh mushrooms',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA67259A324',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Giăm bông',
    description: 'Cured ham',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA61B9A8D61',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Xúc xích Pepperoni cay',
    description: 'Spicy pepperoni sausage',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA6258199C3',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Xúc xích Chorizo cay',
    description: 'Spicy chorizo sausage',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA62D5D6027',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dưa chuột muối chua',
    description: 'Pickled cucumbers',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A21DA51A81211E9EA89958D782B',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cà chua tươi',
    description: 'Fresh tomatoes',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA7AC1A1D67',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Hành tây đỏ',
    description: 'Red onions',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA60AE6464C',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dứa tươi',
    description: 'Fresh pineapple',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A21DA51A81211E9AFA6795BA2A0',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Rau thơm Ý',
    description: 'Italian herbs',
    price: 39000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/370dac9ed21e4bffaf9bc2618d258734.png',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Ớt chuông ngọt',
    description: 'Sweet bell peppers',
    price: 59000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA63F774C1B',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Phô mai Feta viên',
    description: 'Feta cheese cubes',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/000D3A39D824A82E11E9AFA6B0FFC349',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Thịt viên',
    description: 'Meatballs',
    price: 79000,
    imageUrl:
      'https://cdn.dodostatic.net/static/Img/Ingredients/b2f3a5d5afe44516a93cfc0d2ee60088.png',
    isActive: true,
    isRequired: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const products = [
  {
    name: 'Pizza Hải Sản Pesto',
    slug: 'pizza-hai-san-pesto',
    description: 'Pizza với hải sản tươi ngon và sốt Pesto đặc biệt',
    basePrice: 179000,
    imageUrl:
      'https://media.dodostatic.com/image/r:292x292/11ef93517b036e5ca67b43ca2ba0ef12.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza Xúc Xích Ý (Pepperoni)',
    slug: 'pizza-pepperoni',
    description: 'Pizza với xúc xích Ý (Pepperoni) đậm đà',
    basePrice: 169000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef9351d1f5c9e8be730e2e763cba07.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza Half & Half',
    slug: 'pizza-half-half',
    description: 'Pizza kết hợp hai loại nhân khác nhau',
    basePrice: 189000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11eec6d827adfd26a9e97561a6da72c7.avif',
    isActive: true,
    isFeatured: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza Hải Sản Truyền Thống',
    slug: 'pizza-hai-san-truyen-thong',
    description: 'Pizza hải sản truyền thống với hương vị đặc trưng',
    basePrice: 319000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef935194a894b3a481b3ef98075096.avif',
    isActive: true,
    isFeatured: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza 4 Loại Thịt',
    slug: 'pizza-4-loai-thit',
    description: 'Pizza với 4 loại thịt hảo hạng',
    basePrice: 189000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef93515fa332bda9b7b15cc0b8c873.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Pizza 4 Cheese',
    slug: 'pizza-4-cheese',
    description: 'Pizza với 4 loại phô mai đặc trưng',
    basePrice: 179000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef93508e3efc748cfe7a1318d7e73c.avif',
    isActive: true,
    isFeatured: false,
    categoryId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Bánh mì kẹp giăm bông và phô mai',
    slug: 'banh-mi-giam-bong-pho-mai',
    description: 'Bánh mì kẹp giăm bông và phô mai thơm ngon',
    basePrice: 99000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE796FF0059B799A17F57A9E64C725.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mizza Gà Popcorn',
    slug: 'mizza-ga-popcorn',
    description: 'Mizza gà popcorn giòn rụm, độc đáo',
    basePrice: 109000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef935898342902a80f69edfead7a32.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Khoai tây nướng lò với sốt',
    slug: 'khoai-tay-nuong',
    description: 'Khoai tây nướng lò với sốt đặc biệt',
    basePrice: 69000,
    imageUrl:
      'https://media.dodostatic.net/static/Img/Ingredients/000D3A22FA54A81411E9AFA67259A324',
    isActive: true,
    isFeatured: false,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dodster',
    slug: 'dodster',
    description: 'Dodster - món ăn nhanh độc đáo của Dodo Pizza',
    basePrice: 89000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE796F96D11392A2F6DD73599921B9.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Dodster cay',
    slug: 'dodster-cay',
    description: 'Dodster cay nồng, dành cho người thích vị cay',
    basePrice: 89000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE796FD3B594068F7A752DF8161D04.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc chuối',
    slug: 'sua-lac-chuoi',
    description: 'Sữa lắc chuối ngọt ngào, mát lạnh',
    basePrice: 59000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EEE20B8772A72A9B60CFB20012C185.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc táo caramen',
    slug: 'sua-lac-tao-caramen',
    description: 'Sữa lắc táo caramen thơm ngon, độc đáo',
    basePrice: 59000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE79702E2A22E693D96133906FB1B8.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc bánh quy Oreo',
    slug: 'sua-lac-oreo',
    description: 'Sữa lắc bánh quy Oreo, món khoái khẩu của nhiều người',
    basePrice: 59000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE796FA1F50F8F8111A399E4C1A1E3.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sữa lắc truyền thống',
    slug: 'sua-lac-truyen-thong',
    description: 'Sữa lắc truyền thống, hương vị tuổi thơ',
    basePrice: 59000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE796F93FB126693F96CB1D3E403FB.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Cappuccino caramen',
    slug: 'cappuccino-caramen',
    description: 'Cappuccino caramen ấm áp, thơm lừng',
    basePrice: 49000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE7D61AED6B6D4BFDAD4E58D76CF56.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Latte dừa',
    slug: 'latte-dua',
    description: 'Latte dừa béo ngậy, hương vị nhiệt đới',
    basePrice: 49000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE7D61B19FA07090EE88B0ED347F42.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Americano',
    slug: 'americano',
    description: 'Americano đậm đà, cho ngày mới tỉnh táo',
    basePrice: 39000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE7D61B044583596548A59078BBD33.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Latte',
    slug: 'latte',
    description: 'Latte truyền thống, êm dịu',
    basePrice: 49000,
    imageUrl:
      'https://media.dodostatic.net/image/r:292x292/11EE7D61B0C26A3F85D97A78FEEE00AD.webp',
    isActive: true,
    isFeatured: false,
    categoryId: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mì Ý Hải Sản Sốt Pesto',
    slug: 'mi-y-hai-san-pesto',
    description: 'Mì Ý hải sản sốt Pesto, hương vị Địa Trung Hải',
    basePrice: 129000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef935840297bab88e4aae1632cb9bd.avif',
    isActive: true,
    isFeatured: false,
    categoryId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mì Ý Sốt Bò Bằm Xúc Xích',
    slug: 'mi-y-sot-bo-bam',
    description: 'Mì Ý sốt bò bằm và xúc xích, đậm đà',
    basePrice: 129000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/11ef93584c9054ef9b657f6145a806e4.avif',
    isActive: true,
    isFeatured: false,
    categoryId: 6,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const combos = [
  {
    name: 'Combo Mizza + Nước ngọt',
    slug: 'combo-mizza-nuoc-ngot',
    description: 'Combo Mizza kèm nước ngọt, lựa chọn hoàn hảo cho bữa ăn',
    basePrice: 350000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/019362cecca7743f96e2907d17cc2e8e.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo Mizza + Khai vị + Nước ngọt',
    slug: 'combo-mizza-khai-vi-nuoc-ngot',
    description: 'Combo Mizza, khai vị và nước ngọt, đầy đủ cho bữa tiệc',
    basePrice: 450000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/019444bd2d7e71f0a454241811ed5c61.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Combo 2 người Pizza 23cm + 2 Nước ngọt',
    slug: 'combo-2-nguoi-pizza',
    description: 'Combo dành cho 2 người với pizza cỡ vừa và nước ngọt',
    basePrice: 300000,
    imageUrl:
      'https://media.dodostatic.com/image/r:233x233/0193635397bb7069b3200f614052436a.avif',
    isActive: true,
    isFeatured: true,
    categoryId: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const productVariants = [
  {
    productId: 1,
    name: 'Nhỏ (23cm) Mỏng',
    size: '13cm',
    type: 'Mỏng',
    priceModifier: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 1,
    name: 'Lớn (33cm)',
    size: '23cm',
    type: 'Bình thường',
    priceModifier: 14000,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 2,
    name: 'Nhỏ (23cm) Mỏng',
    type: 'Mỏng',
    size: '13cm',
    priceModifier: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 2,
    name: 'Lớn (33cm)',
    size: '33cm',
    type: 'Bình thường',
    priceModifier: 13000,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 3,
    name: 'Lớn (33cm)',
    size: '33cm',
    type: 'Bình thường',
    priceModifier: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 3,
    name: 'Lớn (33cm)',
    size: '23cm',
    type: 'Mỏng',
    priceModifier: 14000,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 4,
    name: 'Lớn (33cm)',
    size: '23cm',
    type: 'Bình thường',
    priceModifier: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    name: 'Lớn (33cm)',
    size: '33cm',
    type: 'Bình thường',
    priceModifier: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    name: 'Lớn (33cm)',
    size: '33cm',
    type: 'Mỏng',
    priceModifier: 14000,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    name: 'Lớn (33cm)',
    size: '33cm',
    type: 'Mỏng',
    priceModifier: 0,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    name: 'Lớn (33cm)',
    size: '33cm',
    type: 'Bình thường',
    priceModifier: 14000,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example ProductIngredients (assuming some default ingredients for products)
export const productIngredients = [
  {
    productId: 1,
    ingredientId: 1,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 1,
    ingredientId: 2,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 2,
    ingredientId: 8,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 7,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 8,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 9,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 5,
    ingredientId: 17,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    ingredientId: 2,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    ingredientId: 3,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    productId: 6,
    ingredientId: 16,
    isDefault: true,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Users
export const users = [
  {
    email: 'customer1@example.com',
    name: 'John',
    phone: '1234567890',
    role: 'customer',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'admin1@example.com',
    name: 'Smith',
    phone: '0987654321',
    role: 'admin',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Addresses
export const addresses = [
  {
    userId: 1,
    street: '123 Main St',
    city: 'Ho Chi Minh City',
    district: 'District 1',
    ward: 'Ben Nghe',
    zipCode: '700000',
    coordinates: '10.7769,106.7009',
    isDefault: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Orders
export const orders = [
  {
    orderNumber: 'ORD001',
    userId: 1,
    addressId: 1,
    status: 'pending',
    paymentStatus: 'pending',
    paymentMethod: 'cash',
    subtotal: 358000,
    deliveryFee: 30000,
    discount: 0,
    total: 388000,
    notes: '',
    estimatedDelivery: '2025-01-01T01:00:00Z',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example OrderItems
export const orderItems = [
  {
    orderId: 1,
    productId: 1,
    variantId: 1,
    quantity: 2,
    unitPrice: 179000,
    totalPrice: 358000,
    customizations: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example OrderItemIngredients
export const orderItemIngredients = [
  {
    orderItemId: 1,
    ingredientId: 1,
    quantity: 1,
    price: 179000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    orderItemId: 1,
    ingredientId: 2,
    quantity: 1,
    price: 79000,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Carts
export const carts = [
  {
    userId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example CartItems
export const cartItems = [
  {
    cartId: 1,
    productId: 2,
    variantId: 3,
    quantity: 1,
    customizations: {},
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example CartItemIngredients
export const cartItemIngredients = [
  {
    cartItemId: 1,
    ingredientId: 8,
    quantity: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Coupons
export const coupons = [
  {
    code: 'SAVE10',
    name: '10% Off',
    description: '10% off on orders above 200000',
    type: 'percentage',
    value: 10,
    minOrderAmount: 200000,
    maxUses: 100,
    currentUses: 0,
    validFrom: new Date(),
    validTo: '2025-12-31T23:59:59Z',
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example UserCoupons
export const userCoupons = [
  {
    userId: 1,
    couponId: 1,
    isUsed: false,
    usedAt: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Example Reviews
export const reviews = [
  {
    userId: 1,
    productId: 1,
    orderId: 1,
    rating: 5,
    comment: 'Delicious pizza!',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
